name: Gcloud SDK Auth Trial
on:
  push:
    branches:
    - master

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:
  Gcloud-Auth:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/1023629556233/locations/global/workloadIdentityPools/github-actions-trial/providers/github-actions'
          service_account: 'github-actions-sa@prj-hotspot-foundations-trials.iam.gserviceaccount.com'
          token_format: 'access_token'
      - name: 'Setup GCloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Setup Docker Builder'
        uses: 'docker/setup-buildx-action@v2'
      - name: 'Setup GCR Credentials'
        run: |-
          gcloud auth configure-docker
      - name: 'Docker Build and Push'
        uses: 'docker/build-push-action@v3'
        with:
          context: ./source/
          push: true
          registry: gcr.io
          tags: |
            $GCP_PROJECT/github-actions-trial:latest
            $GCP_PROJECT/github-actions-trial:$GITHUB_SHA